# fly.toml app configuration file generated for shop-on-merchant on 2023-08-23T16:16:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shop-on-merchant"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
